# Generated by Django 6.0.5 on 2026-05-19 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('merge', 'Unir PDFs'), ('split', 'Dividir PDF'), ('pdf_to_images', 'PDF → Imagens'), ('images_to_pdf', 'Imagens → PDF'), ('pdf_to_text', 'PDF → Texto'), ('ocr_image', 'OCR em Imagem'), ('ocr_pdf', 'OCR em PDF'), ('compress', 'Comprimir PDF'), ('rotate', 'Rotacionar PDF')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('running', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('input_files', models.JSONField(default=list)),
                ('output_file', models.TextField(blank=True)),
                ('params', models.JSONField(default=dict)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF Job',
                'verbose_name_plural': 'PDF Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
