# Generated by Django 6.0.5 on 2026-05-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0002_alter_pdfjob_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfjob',
            name='operation',
            field=models.CharField(choices=[('merge', 'Unir PDFs'), ('split', 'Dividir PDF'), ('pdf_to_images', 'PDF → Imagens'), ('images_to_pdf', 'Imagens → PDF'), ('pdf_to_text', 'PDF → Texto'), ('ocr_image', 'OCR em Imagem'), ('ocr_pdf', 'OCR em PDF'), ('compress', 'Comprimir PDF'), ('rotate', 'Rotacionar PDF'), ('pdf_to_docx', 'PDF → DOCX'), ('pdf_to_docx_ocr', 'PDF → DOCX (OCR)'), ('docx_to_pdf', 'DOCX → PDF'), ('img_convert', 'Converter Imagem'), ('img_crop', 'Cortar Imagem'), ('img_resize', 'Redimensionar Imagem')], max_length=20),
        ),
    ]
