# Generated by Django 6.0.5 on 2026-05-19 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('running', 'Baixando'), ('done', 'Concluído'), ('error', 'Erro'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('speed', models.CharField(blank=True, max_length=50)),
                ('eta', models.CharField(blank=True, max_length=50)),
                ('file_path', models.TextField(blank=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True)),
                ('download_type', models.CharField(default='video', max_length=10)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('subtitles', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['-created_at'],
            },
        ),
    ]
