# Generated by Django 6.0.5 on 2026-05-19 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emulatorjs_core', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Rodando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('roms_path', models.TextField()),
                ('total_found', models.IntegerField(default=0)),
                ('total_new', models.IntegerField(default=0)),
                ('current_file', models.CharField(blank=True, max_length=300)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ROM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file_path', models.TextField(unique=True)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('cover_path', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('players', models.IntegerField(default=1)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('screenscraper_id', models.IntegerField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roms', to='rom_library.platform')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
