# Generated by Django 6.0.5 on 2026-05-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rom_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rom',
            old_name='screenscraper_id',
            new_name='thegamesdb_id',
        ),
    ]
